language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: BNG9xrn1/REnjpkatPXyuFdqYBRnLX7vUTq30DJWjFofWxtjuuDJccfrhM93dmZoaNj22lEu21YKtIXgcfpRaP2GQg9773ErUd0XyvAHnamTDD63ifGRSL+JAyvfanm7N9GWOsy/LR8MbcraT5diGSxhszyukQqH9wmuuVCQkgSMTJxMsQHqk8lFl3hUlBcMCcT8oZBI6srMpQy+skq6oHfZMCkDeC/6eHpe6WZI0x2wsImm4Wu2mBjn/xoxrvPv3S6suOkIAm7R4jX86aOmsM86sx5UVBH3pmMCQe4J/slOiwJG02THnlyVXxV8dB84MIYGnPabyjFKeTFvvr0k0R8HYQzgnWZe/1+yoUW9iv3cSP58+Bxul39xDdmRthkqqHKmwltUtj6cMgVBYve8FI0TgLyS9mepsilM4hBYAhwFsTTQy0VWUYSV4WzpbHhJ31END9OVhvtyTtyujEkeKHcIKZiIvo9DBmOIllbXpnHkcGhjXZLNSGtrY7OhCrnpG2obfe40SW703Ml+t0Sj5ziyLIdyCKahGXFAQGLljy7q7XUuXcJrS+zZysLOnGIS/oKRxBF9XUO0a2OgheoXVS9Ya+VR/HY0aCgd/C22LlQa5QP7zvjop7pTSwL8e/BpseawrJhELORnixGAnZCkymQhF6MUAaSgawidIuWdYwM=
  app: blog-app-mattlong87